# Generated by Django 4.2.6 on 2023-10-15 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import projects.validators
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_eng', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('show_first_page', models.BooleanField(default=False)),
                ('active_eng', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(help_text='The text appears on homepage', max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('title_eng', models.CharField(default='Insert Text', max_length=255)),
                ('short_description_eng', models.CharField(default='Insert Text', help_text='The text appears on homepage', max_length=255)),
                ('description_eng', tinymce.models.HTMLField(default='Insert Text')),
                ('seo_description_eng', models.CharField(blank=True, default='Insert Text', max_length=255, null=True)),
                ('seo_keywords_eng', models.CharField(blank=True, default='Insert Text', max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('day_added', models.DateField(auto_now_add=True)),
                ('href', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('demo', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory')),
            ],
            options={
                'verbose_name_plural': 'Project',
                'ordering': ['-id'],
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('alt', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(upload_to='', validators=[projects.validators.validate_image])),
                ('text', models.TextField(blank=True, null=True, verbose_name='Optional description.')),
                ('active', models.BooleanField(default=True)),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
