# Generated by Django 4.2.6 on 2023-10-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_imageproject_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='active_eng',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='seo_description_eng',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='seo_keywords_eng',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='short_description_eng',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='title_eng',
        ),
    ]
