# Generated by Django 3.2.12 on 2022-08-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190602_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Project'},
        ),
    ]
