# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 05:32
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(help_text='1332*550', upload_to=blog.models.post_upload, verbose_name='Image'),
        ),
    ]
