# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170627_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_eng',
            field=models.TextField(blank=True, help_text='Use Html!!!', null=True, verbose_name='Content_eng'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(help_text='1332*550', upload_to='', verbose_name='Image'),
        ),
    ]
