# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='file',
        ),
    ]
