# Generated by Django 3.2.12 on 2022-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('ticker', models.CharField(max_length=200, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('market_variance', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('camp', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True)),
                ('simply_return', models.DecimalField(decimal_places=8, default=0, help_text='Simply Rate of Return', max_digits=30)),
                ('log_return', models.DecimalField(decimal_places=8, default=0, help_text='Log Return', max_digits=30)),
                ('standard_deviation', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
                ('sharp', models.DecimalField(decimal_places=8, default=0, max_digits=30)),
            ],
        ),
    ]
