# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomepage',
            name='header_message',
        ),
        migrations.RemoveField(
            model_name='welcomepage',
            name='header_message_eng',
        ),
        migrations.RemoveField(
            model_name='welcomepage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='welcomepage',
            name='personal_photo',
        ),
        migrations.RemoveField(
            model_name='welcomepage',
            name='text_message',
        ),
        migrations.RemoveField(
            model_name='welcomepage',
            name='text_message_eng',
        ),
    ]
