# Generated by Django 2.2 on 2020-12-13 10:03

from django.db import migrations, models
import showcase.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('site_related', models.URLField(blank=True)),
                ('text', tinymce.models.HTMLField(blank=True)),
                ('image', models.ImageField(upload_to=showcase.models.upload_location)),
                ('category', models.CharField(choices=[('a', 'Website'), ('b', 'Αφορα Επιχειρισεις'), ('c', 'Λοιπά')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
